name: CMS SideBar
id: CMSSideBar
description: MovableType5にサイドバーを追加するプラグイン
version: 1.0
l10n_lexicon:
  ja: l10n_ja.yaml
callbacks:
  MT::App::CMS::template_source.header: 
    code: $CMSSideBar::CMSSideBar::Plugin::_blog_extras_source
    priority: 2
  MT::App::CMS::template_param.header: 
    code: $CMSSideBar::CMSSideBar::Plugin::_blog_extras_param
    priority: 1
